=== hipolitojimenez/leanspooldao/src/test/resources/dbunit/PrintJobsTestSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://localhost/PrintJobsTest" xmlns:tns="http://localhost/PrintJobsTest" elementFormDefault="qualified">
    <element name="dataset" type="tns:datasetType"></element>
    <complexType name="datasetType">
    	<sequence>
    		<element name="PrintJob" type="tns:printJobType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>
    <complexType name="printJobType">
    	<attribute name="JobId" type="string"></attribute>
    	<attribute name="PrinterName" type="string"></attribute>
    	<attribute name="JobStatus" type="string"></attribute>
    </complexType>
</schema>

=== hipolitojimenez/leanspooldao/src/test/resources/dbunit/PrintJobsTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataset
		xmlns="http://localhost/PrintJobsTest"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://localhost/PrintJobsTest PrintJobsTestSchema.xsd ">
	<PrintJob JobId="jobId02" PrinterName="Printer02" JobStatus="Failed" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId01" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId03" PrinterName="Printer03" JobStatus="Completed" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId04" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId05" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId06" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId07" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId08" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId09" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId10" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId11" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId12" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId13" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId14" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId15" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId16" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId17" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId18" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId19" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId20" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId21" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId22" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId23" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId24" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId25" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId26" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId27" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId28" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId29" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId30" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId31" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId32" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId33" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId34" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId35" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId36" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId37" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId38" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId39" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId40" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId41" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId42" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId43" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId44" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId45" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId46" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId47" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId48" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId49" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId50" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId51" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId52" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId53" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId54" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId55" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId56" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId57" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId58" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId59" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId60" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId61" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId62" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId63" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId64" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId65" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId66" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId67" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId68" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId69" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId70" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId71" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId72" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId73" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId74" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId75" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId76" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId77" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId78" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId79" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId80" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId81" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId82" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId83" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId84" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId85" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId86" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId87" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId88" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId89" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId90" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId91" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId92" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId93" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId94" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId95" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
	<PrintJob JobId="jobId96" PrinterName="Printer01" JobStatus="New" JobData="RGVtbw==" JobSize="4"/>
